version: '2'

services:
  data:
    image: busybox
    volumes:
      - /var/lib/mysql
    command: /bin/true

  db:
    image: mariadb:latest
    container_name: db
    ports:
      - "3306:3306"
    volumes_from:
      - data

    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: voms
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: voms_test

  mail:
    image: jlynn/python-smtp
    ports:
      - "25:25"

  adminserver:
    image: italiangrid/voms-admin-server:latest
    domainname: local.io

    volumes:
        - /etc/voms
        - /etc/grid-security
        - .:/code:ro
        - ~/.jrebel:/home/voms/.jrebel:rw
        - ~/jrebel:/jrebel:ro
        - ~/yourkit:/yourkit:ro
        - ~/git/voms-admin-server/docker/voms-admin-server/setup:/scripts:ro
        - ~/git/orgdb-fake-users/:/orgdb-fake-users:ro
        - ~/git/voms-migrate:/migrate:ro
        # - ~/orgdb:/orgdb:ro

    ports:
       # 20001 is the default yourkit port
       # - "20001:20001"
       # 6002 is the default JMX port used when enabling JMX
       # - "6002:6002"
       # 1044 is the debug port
       - "1044:1044"
       - "8443"

    links:
        - db
        - mail

    environment:
      # This is need for haproxy to properly load balance stuff...
      TCP_PORTS: 8443

      # This is the VOMS Admin configuration
      #
      VOMS_VO_COUNT: 1 # 0 creates 1 VO, 1 two VOs, ...
      VOMS_HOSTNAME: dev.local.io
      MAILHOST: mail
      MYSQL_ROOT_PASSWORD: pwd

      # VOMS_LOG_LEVEL: debug
      VOMS_DEBUG: y

      # Comment the following line to skip tarball installation
      VOMS_DEPLOY_TARBALL: y

      # VOMS_ADMIN_SERVER_PACKAGE_URL: http://ci-01.cnaf.infn.it/download/voms/versions/jenkins-release_voms_packages-13/sl6/x86_64/voms-admin-server-3.5.1-1.el6.centos.noarch.rpm
      # VOMS_ADMIN_SERVER_VERSION: 3.3.3
      # VOMS_DEBUG_SUSPEND: y
      VOMS_PRE_CONFIGURE: y
      # VOMS_SKIP_CONFIGURE: y
      VOMS_UPGRADE_DB: y
      
      #VOMS_LOAD_DB_DUMP: y
      VOMS_DEV_MODE: y

      VOMS_CONFIGURE_OPTIONS: --skip-ca-check --admin-skip-ca-check 
      VOMS_ARGS: --war /code/voms-admin-server/target/voms-admin.war

      # ENABLE_YOURKIT: y
      # ENABLE_JREBEL: y
      # ENABLE_JMX: y
      # HIBERNATE_LOG_LEVEL: DEBUG
      # STRUTS_LOG_LEVEL: DEBUG
    
    extra_hosts:
      - "voms.local.io:192.168.99.101"

  voms:
    image: italiangrid/voms-dev:centos6
    domainname: local.io

    depends_on:
      - db
      - adminserver
      - lb

    cap_add:
      # The capability below is useful to 
      # run gdb
      - SYS_PTRACE

    volumes:
      - $HOME/git/voms-giaco:/voms:ro
      - $HOME/git/voms-mysql-plugin:/voms-mysql-plugin:ro

    volumes_from:
      - adminserver

    ports:
      - "15000:15000"
    
    links:
      - db

    tty: true

    environment:
      # Uncomment to build VOMS from sources
      # inside the container
      VOMS_BUILD_FROM_SOURCES: y

      VOMS_GIT_REPO: file:///voms
      VOMS_GIT_BRANCH: ssl11-andrea

      # Uncomment to build voms-mysql-plugin from
      # source inside the container
      VOMS_BUILD_MYSQL_PLUGIN: y
      VOMS_MYSQL_GIT_REPO: file:///voms-mysql-plugin

      VOMS_MYSQL_GIT_BRANCH: fix/VOMS-748

  lb:
    image: dockercloud/haproxy:latest
    ports:
      - "8443:8443"
      - "1936:1936"

    environment:
      - MODE=tcp
      # - DOCKER_TLS_VERIFY
      # - DOCKER_HOST
      # - DOCKER_CERT_PATH

    volumes:
      # - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
      - /var/run/docker.sock:/var/run/docker.sock

    links:
      - adminserver
