#!/bin/sh
#set -x
RES_COL=40
MOVE_TO_COL="echo -en \\033[${RES_COL}G"
SETCOLOR_SUCCESS="echo -en \\033[1;32m"
SETCOLOR_FAILURE="echo -en \\033[1;31m"
SETCOLOR_WARNING="echo -en \\033[1;33m"
SETCOLOR_NORMAL="echo -en \\033[0;39m"

echo_success() {
  $MOVE_TO_COL
  echo -n "[  "
  $SETCOLOR_SUCCESS
  echo -n $1
  $SETCOLOR_NORMAL
  echo "  ]"
}

echo_failure() {
  $MOVE_TO_COL
  echo -n "[  "
  $SETCOLOR_FAILURE
  echo -n $1
  $SETCOLOR_NORMAL
  echo "  ]"
}

function test_vo {

	local voname="$1"
	set -e
	voms-admin --vo $voname get-vo-name 2>&1 >/dev/null
	retval=$?
   
	if [ $retval -eq 2 ]; then
		echo_failure "Network error: Tomcat is down."
   		return 1
	fi
   	
	if [ $retval -eq 3 ]; then
		echo_failure "SOAP error: VO is not active."
   		return 1
	fi
   
	if [ $retval -eq 1 ]; then
		echo_failure "Service error"
   		return 1
	fi
   	
	if [ $retval -ne 0 ]; then
		echo_failure Failure
		return 1
	fi
   
   echo_success OK
   return 0
}

vos=            # Space-separated list of VOs
function get_vos {
    if [ -d "${GLITE_LOCATION_VAR}/etc/voms-admin" ]; then
        for d in "${GLITE_LOCATION_VAR}"/etc/voms-admin/*; do
       if [ -r "$d/voms.database.properties" ]; then
      vos="$vos `basename $d`"
       fi
   done
   all_vos=yes
    else 
        echo "It seems you don't have any VOs configured yet."
        exit 1
    fi
}


get_vos;

result=0

for vo in $vos; do
    echo -n "Testing $vo: "

    if test_vo $vo; then
   :
    else
   result=1
    fi
done

exit $result
